### PR TITLE
fix(android): handle second tracing init.

### LINKED ISSUE #272: mobile(tracing): second start failed
second start failed on Android, looks like because of the `tracing` module because the problem started at 6e8906a3fa690b011f0cc4da28acf6a2becce2f1 and by looking at the error message

```
D/mycelium( 8296): log: start_myceliumlog.target="mycelmob"log.module_path="mycelmob"log.file="src/lib.rs"log.line=14
E/mycelium( 8296): log: Caught a panic calling rust code: "failed to set global default subscriber: SetGlobalDefaultError(\"a global default trace dispatcher has already been set\")"log.target="uniffi_core::ffi::rustcalls"log.module_path="uniffi_core::ffi::rustcalls"log.file="/Users/ibk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uniffi_core-0.27.2/src/ffi/rustcalls.rs"log.line=195
E/[TunService]( 8296): startMycelium failed with exception
E/[TunService]( 8296): tech.threefold.mycelium.rust.uniffi.mycelmob.InternalException: failed to set global default subscriber: SetGlobalDefaultError("a global default trace dispatcher has already been set")
E/[TunService]( 8296): 	at tech.threefold.mycelium.rust.uniffi.mycelmob.MycelmobKt.uniffiCheckCallStatus(mycelmob.kt:292)
E/[TunService]( 8296): 	at tech.threefold.mycelium.rust.uniffi.mycelmob.MycelmobKt.access$uniffiCheckCallStatus(mycelmob.kt:1)
E/[TunService]( 8296): 	at tech.threefold.mycelium.rust.uniffi.mycelmob.MycelmobKt.startMycelium(mycelmob.kt:1266)
E/[TunService]( 8296): 	at tech.threefold.mycelium.TunService$start$1.invokeSuspend(TunService.kt:104)
E/[TunService]( 8296): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/[TunService]( 8296): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/[TunService]( 8296): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
E/[TunService]( 8296): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
E/[TunService]( 8296): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
E/[TunService]( 8296): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/[TunService]( 8296): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
E/[TunService]( 8296): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### PR DESCRIPTION
**Pull request by iwanbk**
ignore error when register the tracing subscriber as global default because it is harmless.
The error is most likely because it is already registered on the second run.

Fixes #272

### CODE REVIEW

File: mobile/src/lib.rs [hunk 1]
```diff
@@ -12,14 +12,18 @@ fn setup_logging() {
...
+    let subscriber = tracing_subscriber::registry()
         .with(tracing_android::layer("mycelium").expect("failed to setup logger"))
-        .with(targets)
-        .init();
+        .with(targets);
+    if let Err(e) = tracing::subscriber::set_global_default(subscriber) {
+        // the error is expected to happen on second start, we can ignore it.
+        if e.to_string() != "a global default trace dispatcher has already been set" {
+            error!("Failed to set global default subscriber: {}", e);
+        }
```
Comment (LeeSmet) [inline mobile/src/lib.rs:25]: I'm not really a fan of checking based on error string equivalence. Considering this is the only thing which can go wrong, I'd prefer to just check if the call result is an error (`set_global_default(...).is_err()`) instead.

**Review by LeeSmet — CHANGES_REQUESTED** [review]

File: mobile/src/lib.rs (hunk 1 above)
Comment (iwanbk) [reply mobile/src/lib.rs:25]: > I'm not really a fan of checking based on error string equivalence

actually, me as well

> I'd prefer to just check if the call result is an error (set_global_default(...).is_err()) instead.

i think it is basically the same with what i currently do, no?

I will take a look at `once` or something similar

Comment (iwanbk) [reply mobile/src/lib.rs:25]: oh, i think i misunderstood you

> Considering this is the only thing which can go wrong

I'm not sure about this actually, that is why i'm checking for specific error.

Comment (iwanbk) [reply mobile/src/lib.rs]: i improve it using lazy_static, pls check again @LeeSmet

**Review by LeeSmet — APPROVED** [review]
